# Run test suite using tox.
name: Tests

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-20.04
   
    container:
      image: python:3.8-buster
    
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install tox tox-poetry poetry
        
      - name: Run tox
        run: tox

      - name: Upload Coverage Report As Artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

      - name: Run codacy-coverage-reporter
        if: github.event_name == 'push'
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: $GITHUB_WORKSPACE/coverage.xml
