
name: PyPi Publish

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python:3.9-buster

    steps:
        - uses: actions/checkout@v2

        - name: Prepare Distribution
          run: python setup.py sdist

        - name: Deploy To PyPi Using Twine
          run: ls dist/*