# Run test suite using tox.

name: Run tox

on:
  pull_request:
    branches:
      - "*"
        
jobs:

  test:
    runs-on: ubuntu-latest
   
    container:
      image: python:3.9-buster
    
    steps:
      - uses: actions/checkout@v2

      - name: Install tox
        run: pip install tox
        
      - name: Run tox
        run: tox
